/*
    PRACTICA 7 - TEMA 10
    @AUTHOR: ALBERTO JOSE MARUN INDRIAGO
    @DATE: 01 FEBRERO 2021
*/
-- PREGUNTA 1
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (999, 'MEDAC');

-- PREGUNTA 2
INSERT INTO EMPLOYEES
VALUES(27, 'Alberto', 'Marun', 'albertojmarun@gmail.com', '699301994', '27/09/2020', 'SA_REP', 1500, NULL, NULL, NULL);

-- PREGUNTA 3
UPDATE EMPLOYEES
SET DEPARTMENT_ID = 999
WHERE EMPLOYEE_ID = 27;

-- PREGUNTA 4
INSERT INTO EMPLOYEES
SELECT EMPLOYEE_ID + 1000, FIRST_NAME, LAST_NAME, LOWER(EMAIL), PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;

-- PREGUNTA 5
UPDATE EMPLOYEES
SET DEPARTMENT_ID = 999
WHERE EMPLOYEE_ID > 1000;

-- PREGUNTA 6
INSERT INTO EMPLOYEE2
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID > 1000;

-- PREGUNTA 7
UPDATE EMPLOYEE2
SET SALARY = EMPLOYEE_ID + (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 205);

-- PREGUNTA 8
DELETE FROM EMPLOYEE2
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 30);

-- PREGUNTA 9
/*
    NO SE PUEDE BORRAR EL DEPARTMENTO 20, DEBIDO A QUE TIENE EMPLEADOS REGISTRADOS EN DICHO DEPARTAMENTO Y HACIENDO ESTO, SE DEJARIAN EMPLEADOS SUELTOS, QUE NO SE PUEDE HACER.
*/
DELETE FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 20;

-- PREGUNTA 10
DELETE FROM DEPARTMENTS2
WHERE DEPARTMENT_ID = 20;