CREATE OR REPLACE TYPE PERSONA AS OBJECT(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(20),
    APELLIDO VARCHAR2(20),
    MEMBER PROCEDURE SHOW_DNI,
    MEMBER PROCEDURE SHOW_NAME,
    MEMBER PROCEDURE SHOW_LAST_NAME,
    ORDER MEMBER FUNCTION ORDER_BY_DNI(COMPARE PERSONA) RETURN INTEGER
) NOT FINAL;

CREATE OR REPLACE TYPE BODY PERSONA AS
    MEMBER PROCEDURE SHOW_DNI IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('EL DNI DE ' || SELF.NOMBRE || ' ES ' || SELF.DNI);
    END SHOW_DNI;

    MEMBER PROCEDURE SHOW_NAME IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || SELF.NOMBRE );
    END SHOW_NAME;

    MEMBER PROCEDURE SHOW_LAST_NAME IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('APELLIDO: ' || SELF.APELLIDO );
    END SHOW_LAST_NAME;

    ORDER MEMBER FUNCTION ORDER_BY_DNI(COMPARE PERSONA) RETURN INTEGER IS
    BEGIN
        IF(SELF.DNI) < (COMPARE.DNI) THEN RETURN -1;

        ELSIF(SELF.DNI) > (COMPARE.DNI) THEN RETURN 1;

        ELSE RETURN 0;

        END IF;
    END;
END;

CREATE OR REPLACE TYPE ALUMNO UNDER PERSONA(
    CURSO VARCHAR2(50),
    CICLO VARCHAR2(50),
    FALTAS_DE_ASISTENCIA INTEGER,
    MEMBER PROCEDURE SHOW_COURSE,
    MEMBER PROCEDURE SHOW_STUDY,
    MEMBER PROCEDURE SHOW_ABSENCE,
    MEMBER PROCEDURE MODIFY_COURSE(NEW_COURSE VARCHAR2),
    MEMBER PROCEDURE MODIFY_STUDY(NEW_STUDY VARCHAR2),
    MEMBER PROCEDURE MODIFY_ABSENCE(NEW_ABSENCE INTEGER)    
)NOT FINAL;

CREATE OR REPLACE TYPE BODY ALUMNO AS
    MEMBER PROCEDURE SHOW_COURSE IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(SELF.NOMBRE ||  ' ESTUDIA ' || SELF.CURSO );
    END SHOW_COURSE;

    MEMBER PROCEDURE SHOW_STUDY IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(SELF.NOMBRE || ' ESTUDIA ' || SELF.CICLO );
    END SHOW_STUDY;

    MEMBER PROCEDURE SHOW_ABSENCE IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(SELF.NOMBRE || ' HA FALTADO ' || SELF.FALTAS_DE_ASISTENCIA );
    END SHOW_ABSENCE;

    MEMBER PROCEDURE MODIFY_COURSE(NEW_COURSE VARCHAR2) IS
    BEGIN
        SELF.CURSO := NEW_COURSE;
    END MODIFY_COURSE;

    MEMBER PROCEDURE MODIFY_STUDY(NEW_STUDY VARCHAR2) IS
    BEGIN
        SELF.CICLO := NEW_STUDY;
    END MODIFY_STUDY;

    MEMBER PROCEDURE MODIFY_ABSENCE(NEW_ABSENCE INTEGER) IS
    BEGIN
        SELF.FALTAS_DE_ASISTENCIA := NEW_ABSENCE;
    END MODIFY_ABSENCE;
END;

DECLARE
    ALBERTO ALUMNO;
    JUAN ALUMNO;
    BEGIN
        ALBERTO := NEW ALUMNO('123456788', 'ALBERTO', 'MARUN', 'DAW', 'BASE DE DATOS', 0);
        JUAN := NEW ALUMNO('123456789', 'JUAN', 'MONTERO', 'DAM', 'PROGRAMACION', 0);
        
        ALBERTO.SHOW_DNI;
        ALBERTO.SHOW_NAME;
        ALBERTO.SHOW_LAST_NAME;
        ALBERTO.SHOW_COURSE;
        ALBERTO.SHOW_STUDY;
        ALBERTO.SHOW_ABSENCE;
        
        DBMS_OUTPUT.PUT_LINE('');
        
        JUAN.SHOW_DNI;
        JUAN.SHOW_NAME;
        JUAN.SHOW_LAST_NAME;
        JUAN.SHOW_COURSE;
        JUAN.SHOW_STUDY;
        JUAN.SHOW_ABSENCE;
        
        DBMS_OUTPUT.PUT_LINE('');
        
        IF(JUAN.ORDER_BY_DNI(ALBERTO) = 1) THEN
            JUAN.SHOW_DNI;
        ELSE
            ALBERTO.SHOW_DNI;
        END IF;
END;