-- PROCEDIMIENTO
CREATE OR REPLACE
PROCEDURE indicar_fecha IS
    fecha DATE;
BEGIN
    SELECT SYSDATE INTO fecha FROM DUAL;
    DBMS_OUTPUT.PUT_LINE(fecha);
END indicar_fecha;

-- FUNCION
CREATE OR REPLACE
FUNCTION MULTIPLICAR (VAR1 NUMBER, VAR2 NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN VAR1 * VAR2;
END MULTIPLICAR;

-- USANDO LA FUNCION
SELECT MULTIPLICAR(7, 7) from dual;

-- DECLARANDO 