-- TEMA 10 BASE DE DATOS

/*
    Se puede hacer uso de la herramienta gráfica
    PERO NO ES NADA RECOMENDABLE.
*/

-- Insertar un nuevo registro.

/*
    INSERT INTO tabla (campo1, campo2, campo3...)
    VALUES (valor1, valor2, );
*/
INSERT INTO EMPLOYEES ()
    VALUES ();

-- INSERT INTO tabla VALUES (valor1, valor2, );
INSERT INTO EMPLOYEES VALUES ();

-- ACTUALIZAR LA BASE DE DATOS
/*
    UPDATE tabla
    SET columna1 = valor, columna2 = valor...
    WHERE Condición
*/

UPDATE EMPLOYEES
SET SALARY = x
WHERE DEPARTMENT_ID = x;

-- ELIMINAR UN REGISTRO
/*
    DELETE FROM tabla
    WHERE condición
*/

DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID = x;

-- TEMA 10 - EJEMPLO
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID)
VALUES (10, 'ANTONIO', 'GARCIA', 'Agarcia@yahoo.es', '27/01/2021', 'PR_REP');

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (10, 20);

UPDATE EMPLOYEES
SET HIRE_DATE = '01/01/2020'
WHERE EMPLOYEE_ID IN (10, 20);

DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (10, 20);

-- CREAR UNA NUEVA TABLA
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON(D.DEPARTMENT_ID = E.DEPARTMENT_ID)
WHERE D.DEPARTMENT_ID = 50;

INSERT INTO PRUEBA VALUES 
    (SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_ID, d.DEPARTMENT_NAME
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D ON(D.DEPARTMENT_ID = E.DEPARTMENT_ID)
    WHERE D.DEPARTMENT_ID = 50);

SELECT * FROM PRUEBA;

-- INCREMENTAR EL SALARIO UN 20%
UPDATE EMPLOYEES SET SALARY = SALARY * 1.20
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 20);

SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;