-- TEMA 10 BASE DE DATOS

/*
    Se puede hacer uso de la herramienta gráfica
    PERO NO ES NADA RECOMENDABLE.
*/

-- Insertar un nuevo registro.

/*
    INSERT INTO tabla (campo1, campo2, campo3...)
    VALUES (valor1, valor2, );
*/
INSERT INTO EMPLOYEES ()
    VALUES ();

-- INSERT INTO tabla VALUES (valor1, valor2, );
INSERT INTO EMPLOYEES VALUES ();

-- ACTUALIZAR LA BASE DE DATOS
/*
    UPDATE tabla
    SET columna1 = valor, columna2 = valor...
    WHERE Condición
*/

UPDATE EMPLOYEES
SET SALARY = x
WHERE DEPARTMENT_ID = x;

-- ELIMINAR UN REGISTRO
/*
    DELETE FROM tabla
    WHERE condición
*/

DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID = x;

-- TEMA 10 - EJEMPLO
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID)
VALUES (10, 'ANTONIO', 'GARCIA', 'Agarcia@yahoo.es', '27/01/2021', 'PR_REP');

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (10, 20);

UPDATE EMPLOYEES
SET HIRE_DATE = '01/01/2020'
WHERE EMPLOYEE_ID IN (10, 20);

DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (10, 20);

-- CREAR UNA NUEVA TABLA
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON(D.DEPARTMENT_ID = E.DEPARTMENT_ID)
WHERE D.DEPARTMENT_ID = 50;

INSERT INTO PRUEBA (employee_id, FIRST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES 
    (SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_ID, d.DEPARTMENT_NAME
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D ON(D.DEPARTMENT_ID = E.DEPARTMENT_ID)
    WHERE D.DEPARTMENT_ID = 50);

SELECT * FROM PRUEBA;

-- INCREMENTAR EL SALARIO UN 20%
UPDATE EMPLOYEES SET SALARY = SALARY * 1.20
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 20);

SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

-- EJEMPLO ALUMNOS
  CREATE TABLE "HR"."APROBADOS" 
   (	"DNI" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"NOTA" FLOAT(126), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	 CONSTRAINT "APROBADOS_PK" PRIMARY KEY ("DNI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

INSERT ALL
    INTO ALUMNOS(DNI, NOMBRE, APELLIDO, NOTA) VALUES ('12345678A', 'ALBERTO', 'MARUN', 9)
    INTO ALUMNOS(DNI, NOMBRE, APELLIDO, NOTA) VALUES ('12345678B', 'JUAN', 'MONTERO', 8)
    INTO ALUMNOS(DNI, NOMBRE, APELLIDO, NOTA) VALUES ('12345678C', 'CLAUDIA', 'AURE', 8.5)
    INTO ALUMNOS(DNI, NOMBRE, APELLIDO, NOTA) VALUES ('12345678D', 'MARIA', 'GARCES', 3)
    INTO ALUMNOS(DNI, NOMBRE, APELLIDO, NOTA) VALUES ('12345678E', 'ANA', 'MARULANDA', 4.7)
    SELECT * FROM dual;
    
    
    SELECT DNI, NOTA FROM ALUMNOS WHERE NOTA >= 5;
    
    INSERT INTO APROBADOS SELECT DNI, NOTA FROM ALUMNOS WHERE NOTA >= 5;
    
    SELECT ALUMNOS.DNI, ALUMNOS.NOMBRE INTO APROBADOS FROM ALUMNOS WHERE NOTA < 4;